name: Build Saree Plate

on:
  repository_dispatch:
    types: [process_plate]

jobs:
  plate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SA_JSON: ${{ secrets.SA_JSON }}
      FINISHED_FOLDER_ID: ${{ secrets.FINISHED_FOLDER_ID }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run plate maker
      env:
        FILE_ID: ${{ github.event.client_payload.fileId }}
        CATALOG: ${{ github.event.client_payload.catalog }}
        DESIGN:  ${{ github.event.client_payload.design }}
      run: python runner.py
